services:
  - type: web
    name: twitter-dm-app
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt && cd demodev && python manage.py collectstatic --noinput && python manage.py migrate
    startCommand: cd demodev && gunicorn demodev.wsgi:application
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: twitter-db
          property: connectionString
      - key: ALLOWED_HOSTS
        value: "tweetapp-wn3f.onrender.com,*.onrender.com,localhost,127.0.0.1"
      - key: PYTHONUNBUFFERED
        value: "1"

databases:
  - name: twitter-db
    databaseName: twitter_db
    user: twitter_user
    plan: free
