services:
  - type: web
    name: twitter-dm-app
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate
    startCommand: gunicorn demodev.wsgi:application
    envVars:
      - key: DEBUG
        value: "False"
      - key: PYTHON_VERSION
        value: "3.11"
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: twitter-db
          property: connectionString

databases:
  - name: twitter-db
    databaseName: twitter_db
    user: twitter_user
    plan: free
